version: "3.9"

services:
  node-server:
    build: ./
    environment:
      - PORT=8080
      - REDIS_URL=redis://redis-server:6379
    volumes:
      - ./:/usr/src/app
    ports:
      - 40500:8080
    depends_on:
      - redis-server

  redis-server:
    image: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./redis-data:/var/lib/redis
